# Generated by Django 4.0 on 2022-01-21 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_patientcomments'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientcomments',
            name='comment',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
