name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    
    runs-on: ubuntu-latest

    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: actions/checkout@v2
# #     - name: Build the Docker image
# #       run: | 
# #         ls
# #         docker build . -t trycodeinc/health:$(GITHUB_SHA)
#         docker push trycodeinc/health:$(GITHUB_SHA)

    -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: trycodeinc/health:latest
          
    -   name: AWS SSM Send-Command
        uses: peterkimzz/aws-ssm-send-command@master
        id: ssm
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          instance-ids: ${{ secrets.INSTANCE_ID }}

          command: wget https://raw.githubusercontent.com/sonukumar-a11/finalbackend/master/docker-compose.yml -O docker-compose.yml 
            
    -   name: AWS SSM Send-Command
        uses: peterkimzz/aws-ssm-send-command@master
        id: ssm1
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          instance-ids: ${{ secrets.INSTANCE_ID }}

          command:  wget https://raw.githubusercontent.com/sonukumar-a11/finalbackend/master/wait-for-it.sh -O wait-for-it.sh
            wget https://raw.githubusercontent.com/sonukumar-a11/finalbackend/master/docker-entrypoint.sh -O docker-entrypoint.sh
            sudo docker-compose up --build
    -   name: AWS SSM Send-Command
        uses: peterkimzz/aws-ssm-send-command@master
        id: ssm2
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          instance-ids: ${{ secrets.INSTANCE_ID }}

          command: wget https://raw.githubusercontent.com/sonukumar-a11/finalbackend/master/docker-entrypoint.sh -O docker-entrypoint.sh
            sudo docker-compose up --build
    -   name: AWS SSM Send-Command
        uses: peterkimzz/aws-ssm-send-command@master
        id: ssm4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          instance-ids: ${{ secrets.INSTANCE_ID }}

          command: sudo docker-compose up --build
   
      
  
